### ISSUE TITLE
Feature Request: Allow creating users & teams as an admin

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#72]
Currently there appears to be no way to create new users (and hence teams) as an admin when logged in.

**Comment by GaryA** [comment]
True. New users can only be created when not signed in, since creating an account also signs the user in to the new account.This is tied to the default Yii behaviour so not sure how much would get broken if this were implemented.On 4 Oct 2017 8:47 a.m., cjsoftuk <notifications@github.com> wrote:Currently there appears to be no way to create new users (and hence teams) as an admin when logged in.

**Comment by GaryA** [comment]
Changing this behaviour would break the built-in Yii user signup functionality. Also it's only a couple of extra clicks to log out as admin and create/sign in a new user/team and add their robots. It's more important that users can create their own accounts, either online or at an event.
To avoid the danger of breaking the whole online and local signup this feature will not be added.

**Comment by cjsoftuk** [comment]
Understood Gary - and thanks for taking the time to look into it.
