### ISSUE TITLE
Antlog fails to work correctly when running "non-standard" MySQL setups

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#75]
The code logic ensures that at least 8 robots are present before attempting to generate the fight list.  However, under the following set of circumstances, no valid matches are then generated which leads to a "Trying to get property of a non-object" error in Line 70 of antlog/controllers/FightsController.php.

Team | Robots | No. Entries
-- | -- | --
Team 4 | Robot5, Robot6, Robot 8 | 3
Team 1 | Robot1, Robot2 | 2
Team 3 | Robot4, Robot 7 | 2
Team 2 | Robot3 | 1

**Comment by cjsoftuk** [comment]
I have done further debugging on this and it looks like this only becomes a problem if MySQL is set up to not use the default auto_increment value.

As the MySQL server I put this on is replicated master-master, all robots have odd IDs and this seems to cause a problem.  I'm in the process of testing this hunch now.

**Comment by cjsoftuk** [comment]
Eventually figure this one out (too early in the morning!) to be nothing to do with the database side of things at all:

In setupEvent starting at antlog/models/Fights.php:417, it uses the group index to determine which robotXId field to update using $this->_startMap.  This whole section only appears to work properly if there are 16 robots per group.  Anything less than 9 robots per group causes a problem as robot2Id never gets updated.

**Comment by cjsoftuk** [comment]
Thinking about this further.... surely this should be generating byes as appropriate..... (It doesn't appear to do so on my currently running version).

**Comment by cjsoftuk** [comment]
Aha.... so I was onto something with the database issue.  It *would* generate byes as appropriate, if the assumption it made about the database IDs only auto_incrementing by 1 was correct.

I have, since, renumbered the fights in the aws_fights table in my database to be 1-255.

This primarily came about from running Antlog against MySQL on a Master-Master replicated pair.

Two things from this:
1) I acknowledge this is a non-standard setup
2) Probably ought to be noted somewhere this isn't supported.

**Comment by GaryA** [comment]
This particular scenario fails because an 8-way competition has 2 groups of 4 robots but you have one team of 3 so it's impossible to put the 3 robots in different groups. It should fail in a better way in these circumstances...On 27 Oct 2017 7:32 a.m., cjsoftuk <notifications@github.com> wrote:The code logic ensures that at least 8 robots are present before attempting to generate the fight list.  However, under the following set of circumstances, no valid matches are then generated which leads to a "Trying to get property of a non-object" error in Line 70 of antlog/controllers/FightsController.php.
TeamRobotsNo. EntriesTeam 4Robot5, Robot6, Robot 83Team 1Robot1, Robot22Team 3Robot4, Robot 72Team 2Robot31

**Comment by cjsoftuk** [comment]
Ok, so we've actually got a couple of issues here. How do you want to handle them?

1) For the impossible configuration of robots/groups
2) For the mysql configuration affecting how Antlog works

**Comment by GaryA** [comment]
1 is a bug that needs defining, confirming and fixing
2 The (most common) auto_increment increment value = 1 is assumed and hard-coded into various tables. This is a restriction that almost no users will ever see (or even be aware that a value other than 1 is possible).
This should be noted as a restriction in the "advanced" documentation to avoid confusing the average user.
