### ISSUE TITLE
Database export occurs before closing sign-ups

### ISSUE THREAD

**Issue by cjsoftuk** [GaryA/antlog#79]
The database dump I took on Monday from the online AntLog appears to have exported AWS53 in "Registration" state rather than "Closed".  This means that I have no way of closing it.

Surely the closing of the event should happen before the export?

**Comment by GaryA** [comment]
This is probably a bug but there are several workarounds.1 Since the event is now closed, downloading the database again will have the event in the correct state.2 Edit the state of the event directly in phpmyadmin, AFAIR it's an enumerated field.3 It may be possible to "download" the database from the local installation to change the state, but I'm not sure this is an option if Antlog is configured in "local" mode.4 It may not matter. Even when an event is closed local signups are permitted. Once all entries have been confirmed (usually at tech check) the event can be started. Not sure if the "do draw" button only appears if state is closed.

**Comment by cjsoftuk** [comment]
Thanks Gary - have updated the database and all seems well.  

Do Draw does only appear if state = closed.
