### ISSUE TITLE
Export Feature potentially violates UK Data Protection Laws & GDPR

### ISSUE THREAD

**Issue by loftyD** [GaryA/antlog#98]
I've signed up to Antlog and to my horror, I've noticed there was an Export button, so I clicked it, now I have and can see everyone's user data. At least with the information that was required from me, this would constitute as PII (Personably Identifying Information) breach.

I would recommend for the short term remove the export button and look at proper versioning for your sql. Doctrine would probably be the best tool to start doing that; but in addition, supply a 'bare essential' sql which contains the necessary DDL and DML statements, which does not include information that relates to the user; so that if someone wants to use antlog on their own systems, they have a copy but not with everyones data.

**Comment by cjsoftuk** [comment]
While I understand the concern here (and bear in mind this isn't my code), this isn't immediately trivial to fix.  Teams are bound to users, robots are bound to teams by using foreign keys.  The result is that the user entries must exist in the export for people to be able to run the local copy used at events.

You can't run an Antlog event (at all) in the Online copy, so you have to be able to move data between multiple instances at the moment as the EO has to run it locally.  This is so EOs can cope with venues with no internet access.

Removing the Export button will prevent anyone running any events - which isn't a practical option with an AWS coming up in just over 4 weeks.

I do understand the concern, and yes, I think things can be done better, but this is not a five minute fix.  I'll leave it for Gary to pass further comment about this.

**Comment by GaryA** [comment]
If the export data includes real email addresses that is a bug. If you read the privacy statement you will see that I take data protection seriously and the exported data deliberately never included real email addresses. This has been part of antlog since day 1. Take a look at previous releases if you like. I can't do anything about it until I get home next week. On 30 May 2019 08:47, cjsoftuk <notifications@github.com> wrote:While I understand the concern here (and bear in mind this isn't my code), this isn't immediately trivial to fix.  Teams are bound to users, robots are bound to teams by using foreign keys.  The result is that the user entries must exist in the export for people to be able to run the local copy used at events.
You can't run an Antlog event (at all) in the Online copy, so you have to be able to move data between multiple instances at the moment as the EO has to run it locally.  This is so EOs can cope with venues with no internet access.
Removing the Export button will prevent anyone running any events - which isn't a practical option with an AWS coming up in just over 4 weeks.
I do understand the concern, and yes, I think things can be done better, but this is not a five minute fix.  I'll leave it for Gary to pass further comment about this.

**Comment by GaryA** [comment]
OK Ben Hassan, I've just checked and the downloaded file gives every email address as email@example.com There are no real addresses in that file!On 31 May 2019 22:06, Gary Aylward <gary.aylward@ntlworld.com> wrote:If the export data includes real email addresses that is a bug. If you read the privacy statement you will see that I take data protection seriously and the exported data deliberately never included real email addresses. This has been part of antlog since day 1. Take a look at previous releases if you like. I can't do anything about it until I get home next week. On 30 May 2019 08:47, cjsoftuk <notifications@github.com> wrote:While I understand the concern here (and bear in mind this isn't my code), this isn't immediately trivial to fix.  Teams are bound to users, robots are bound to teams by using foreign keys.  The result is that the user entries must exist in the export for people to be able to run the local copy used at events.
You can't run an Antlog event (at all) in the Online copy, so you have to be able to move data between multiple instances at the moment as the EO has to run it locally.  This is so EOs can cope with venues with no internet access.
Removing the Export button will prevent anyone running any events - which isn't a practical option with an AWS coming up in just over 4 weeks.
I do understand the concern, and yes, I think things can be done better, but this is not a five minute fix.  I'll leave it for Gary to pass further comment about this.

**Comment by GaryA** [comment]
Email addresses are not exported.
